version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rishi123vg
    volumes:
      - ./std.sql:/docker-entrypoint-initdb.d/std.sql
